output   = "genmodels"
wipe     = true
no-tests = true

[psql]
dbname = "gelatin"
host   = "localhost"
port   = 5432
user   = "otto"
pass   = "letmeinnow"
blacklist = ["migrations"]
sslmode = "disable"